Layout/LineLength:
  Max: 120
  Exclude:
    - '*.gemspec'
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 50
Style/OptionalBooleanParameter:
  Enabled: false
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false